import { Feature } from '@/modules/subscription-plans/domain/enums/feature';

export const PlanRules = {
  free: {
    [Feature.TRADE_ACCOUNTS]: { isAllowed: true, limit: 1 },
    [Feature.TRADE_JOURNAL]: { isAllowed: true, historyDays: 30 },
    [Feature.LEARNING_LIST]: { isAllowed: true, limit: 5 },
    [Feature.PERFORMANCE_STATS]: { isAllowed: true, type: 'basic' },
    [Feature.ECONOMIC_CALENDAR]: { isAllowed: false },
    [Feature.RISK_CALCULATOR]: { isAllowed: false },
    [Feature.PAIR_CORRELATION]: { isAllowed: false },
    [Feature.CLASSES]: { isAllowed: false },
    [Feature.COMMUNITY]: { isAllowed: false },
    [Feature.RANKINGS]: { isAllowed: false },
    [Feature.GOAL_SETTING]: { isAllowed: false },
    [Feature.REWARDS]: { isAllowed: false },
    [Feature.CUSTOM_ALERTS]: { isAllowed: false },
    [Feature.DATA_EXPORT]: { isAllowed: false },
    [Feature.AI_REPORTS]: { isAllowed: false },
  },
  basic: {
    [Feature.TRADE_ACCOUNTS]: { isAllowed: true, limit: 5 },
    [Feature.TRADE_JOURNAL]: { isAllowed: true, historyDays: Infinity },
    [Feature.LEARNING_LIST]: { isAllowed: true, limit: 20 },
    [Feature.PERFORMANCE_STATS]: { isAllowed: true, type: 'middle' },
    [Feature.ECONOMIC_CALENDAR]: { isAllowed: true },
    [Feature.RISK_CALCULATOR]: { isAllowed: true },
    [Feature.PAIR_CORRELATION]: { isAllowed: true },
    [Feature.CLASSES]: { isAllowed: false },
    [Feature.COMMUNITY]: { isAllowed: false },
    [Feature.RANKINGS]: { isAllowed: false },
    [Feature.GOAL_SETTING]: { isAllowed: false },
    [Feature.REWARDS]: { isAllowed: false },
    [Feature.CUSTOM_ALERTS]: { isAllowed: false },
    [Feature.DATA_EXPORT]: { isAllowed: false },
    [Feature.AI_REPORTS]: { isAllowed: false },
  },
  pro: {
    [Feature.TRADE_ACCOUNTS]: { isAllowed: true, limit: Infinity },
    [Feature.TRADE_JOURNAL]: { isAllowed: true, historyDays: Infinity },
    [Feature.LEARNING_LIST]: { isAllowed: true, limit: Infinity },
    [Feature.PERFORMANCE_STATS]: { isAllowed: true, type: 'advanced' },
    [Feature.ECONOMIC_CALENDAR]: { isAllowed: true },
    [Feature.RISK_CALCULATOR]: { isAllowed: true },
    [Feature.PAIR_CORRELATION]: { isAllowed: true },
    [Feature.CLASSES]: { isAllowed: true },
    [Feature.COMMUNITY]: { isAllowed: true },
    [Feature.RANKINGS]: { isAllowed: true },
    [Feature.GOAL_SETTING]: { isAllowed: true },
    [Feature.REWARDS]: { isAllowed: false },
    [Feature.CUSTOM_ALERTS]: { isAllowed: false },
    [Feature.DATA_EXPORT]: { isAllowed: false },
    [Feature.AI_REPORTS]: { isAllowed: false },
  },
  premium: {
    [Feature.TRADE_ACCOUNTS]: { isAllowed: true, limit: Infinity },
    [Feature.TRADE_JOURNAL]: { isAllowed: true, historyDays: Infinity },
    [Feature.LEARNING_LIST]: { isAllowed: true, limit: Infinity },
    [Feature.PERFORMANCE_STATS]: { isAllowed: true, type: 'advanced' },
    [Feature.ECONOMIC_CALENDAR]: { isAllowed: true },
    [Feature.RISK_CALCULATOR]: { isAllowed: true },
    [Feature.PAIR_CORRELATION]: { isAllowed: true },
    [Feature.CLASSES]: { isAllowed: true },
    [Feature.COMMUNITY]: { isAllowed: true },
    [Feature.RANKINGS]: { isAllowed: true },
    [Feature.GOAL_SETTING]: { isAllowed: true },
    [Feature.REWARDS]: { isAllowed: true },
    [Feature.CUSTOM_ALERTS]: { isAllowed: true },
    [Feature.DATA_EXPORT]: { isAllowed: true },
    [Feature.AI_REPORTS]: { isAllowed: true },
  },
} as const;
