-- AlterTable
ALTER TABLE "journal_detail_mt5" ALTER COLUMN "ticket" SET DATA TYPE TEXT,
ALTER COLUMN "orderId" SET DATA TYPE TEXT,
ALTER COLUMN "positionId" SET DATA TYPE TEXT,
ALTER COLUMN "magic" SET DATA TYPE TEXT;
