export const MT5DealTypeToDomain: Record<string, string> = {
  DEAL_TYPE_BUY: 'BUY',
  DEAL_TYPE_SELL: 'SELL',
  DEAL_TYPE_BALANCE: 'BALANCE',
  DEAL_TYPE_CREDIT: 'CREDIT',
  DEAL_TYPE_CHARGE: 'ADDITIONAL_CHARGE',
  DEAL_TYPE_CORRECTION: 'CORRECTION',
  DEAL_TYPE_BONUS: 'BONUS',
  DEAL_TYPE_COMMISSION: 'COMMISSION',
  DEAL_TYPE_COMMISSION_DAILY: 'COMMISSION_DAILY',
  DEAL_TYPE_COMMISSION_MONTHLY: 'COMMISSION_MONTHLY',
  DEAL_TYPE_COMMISSION_AGENT_DAILY: 'AGENT_DAILY',
  DEAL_TYPE_COMMISSION_AGENT_MONTHLY: 'AGENT_MONTHLY',
  DEAL_TYPE_INTEREST: 'INTEREST',
  DEAL_TYPE_BUY_CANCELED: 'BUY_CANCELED',
  DEAL_TYPE_SELL_CANCELED: 'SELL_CANCELED',
  DEAL_DIVIDEND: 'DIVIDEND',
  DEAL_DIVIDEND_FRANKED: 'DIVIDEND_FRANKED',
  DEAL_TAX: 'TAX',
  UNKNOWN: 'UNKNOWN',
};

export const MT5DealEntryToDomain: Record<string, string> = {
  DEAL_ENTRY_IN: 'IN',
  DEAL_ENTRY_OUT: 'OUT',
  DEAL_ENTRY_INOUT: 'INOUT',
  DEAL_ENTRY_OUT_BY: 'OUT_BY',
  UNKNOWN: 'UNKNOWN',
};

export const MT5DealReasonToDomain: Record<string, string> = {
  DEAL_REASON_CLIENT: 'CLIENT',
  DEAL_REASON_MOBILE: 'MOBILE',
  DEAL_REASON_WEB: 'WEB',
  DEAL_REASON_EXPERT: 'EXPERT',
  DEAL_REASON_SL: 'STOP_LOSS',
  DEAL_REASON_TP: 'TAKE_PROFIT',
  DEAL_REASON_SO: 'STOP_OUT',
  DEAL_REASON_ROLLOVER: 'ROLLOVER',
  DEAL_REASON_VMARGIN: 'VMARGIN',
  DEAL_REASON_SPLIT: 'SPLIT',
  DEAL_REASON_CORPORATE_ACTION: 'CORPORATE_ACTION',
  UNKNOWN: 'UNKNOWN',
};
